version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r src/lambda_function/requirements.txt -t src/lambda_function/
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Building the Lambda package...
      - cd src/lambda_function
      - zip -r ../lambda_function.zip .
  post_build:
    commands:
      - echo Build completed on `date`